version: 2
updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
    day: friday
    time: '18:00'
    timezone: Asia/Tokyo
  open-pull-requests-limit: 99
  reviewers:
  - LaurenceGA
  labels:
  - dependencies
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: weekly
    day: friday
    time: '18:00'
    timezone: Asia/Tokyo
  open-pull-requests-limit: 99
  reviewers:
  - LaurenceGA
  labels:
  - dependencies
