linters-settings:
  gocognit:
    min-complexity: 10
  gocyclo:
    min-complexity: 10
  godot:
    check-all: true
  nestif:
    min-complexity: 3
  gomodguard:
    allowed:
      domains:
        - github.com
        - golang.org
        - gopkg.in

linters:
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - errcheck
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - golint
    - gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - rowserrcheck
    - scopelint
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace
    - gochecknoglobals
    - gocognit
    - godox
    - prealloc
    - wsl
    - asciicheck
    - godot
    - goerr113
    - gomodguard
    - nestif
    - nolintlint
    - cyclop
    - durationcheck
    - errorlint
    - exhaustive
    - exportloopref
    - forcetypeassert
    - goheader
    - ifshort
    - importas
    - makezero
    - nilerr
    - nlreturn
    - noctx
    - predeclared
    - revive
    - sqlclosecheck
    - thelper
    - wastedassign

issues:
  exclude-rules:
    - path: .*/mock(s)?/generate\.go
      linters:
        - lll
    - path: .*_test.go
      linters:
        - gomnd
        - funlen
        - goerr113

# golangci.com configuration
# https://github.com/golangci/golangci/wiki/Configuration
service:
  golangci-lint-version: 1.37.x # use the fixed version to not introduce new linters unexpectedly
