// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package di

import (
	"github.com/LaurenceGA/go-crev/internal/git"
	"github.com/LaurenceGA/go-crev/internal/store"
)

// Injectors from wire.go:

func InitialiseStoreFetcher() *store.Fetcher {
	client := git.NewClient()
	fetcher := store.NewFetcher(client)
	return fetcher
}
