name: Master checks

on:
  push:
    branches:
      - master

jobs:
  lint:
    name: golangci lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2.3.2
      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v1.10.1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-check